/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package luas.keliling.bangun.datar;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class Balok extends javax.swing.JFrame {
    double panjang, lebar, tinggi, luas, keliling, volume;
    {
        JPanel jp = new JPanel();
        JTextField jt = new JTextField(40);
    }
    /**
     * Creates new form Balok
     */
    public Balok() {
        initComponents();
        
        TfLuas.setEditable(false);
        TfKeliling.setEditable(false);
        TfVolume.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TfPanjang = new javax.swing.JTextField();
        TfLebar = new javax.swing.JTextField();
        TfTinggi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TfHitung = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Hapus = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        CBLuas = new javax.swing.JCheckBox();
        CBKeliling = new javax.swing.JCheckBox();
        CBVolume = new javax.swing.JCheckBox();
        TfLuas = new javax.swing.JTextField();
        TfKeliling = new javax.swing.JTextField();
        TfVolume = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Balok");

        jLabel2.setText("Rumus Luas:");

        jLabel3.setText("Rumus Keliling:");

        jLabel4.setText("Rumus Volume:");

        jLabel5.setText("Masukan Panjang:");

        jLabel6.setText("Masukan Lebar:");

        jLabel7.setText("Masukan Tinggi:");

        jLabel9.setText("4 (Panjang + Lebar + Tinggi)");

        jLabel10.setText("Panjang x Lebar x Tinggi");

        TfPanjang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfPanjangKeyTyped(evt);
            }
        });

        TfLebar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfLebarKeyTyped(evt);
            }
        });

        TfTinggi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfTinggiKeyTyped(evt);
            }
        });

        jLabel11.setText("Hasil");

        TfHitung.setText("Hitung");
        TfHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfHitungActionPerformed(evt);
            }
        });

        jLabel12.setText("Luas:");

        jLabel13.setText("Keliling:");

        jLabel14.setText("Volume:");

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        jLabel15.setText("2 (Panjang x Lebar) + (Lebar x Tinggi) + (Panjang x Tinggi)");

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        CBLuas.setText("Luas");

        CBKeliling.setText("Keliling");

        CBVolume.setText("Volume");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(28, 28, 28)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TfLuas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfVolume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TfPanjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(TfLebar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfTinggi, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBLuas)
                                    .addComponent(CBKeliling)
                                    .addComponent(CBVolume))
                                .addGap(20, 20, 20))))
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addComponent(CBLuas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TfPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBKeliling))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TfLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBVolume))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TfTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TfLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(TfHitung))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kembali)
                    .addComponent(Keluar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfHitungActionPerformed
        // TODO add your handling code here:
        String rumus;
        rumus="";
        if(CBLuas.isSelected() && CBKeliling.isSelected() && CBVolume.isSelected()){
            // LUAS
            panjang = Double.parseDouble(this.TfPanjang.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            luas = 2 * (panjang * lebar) + (lebar * tinggi) + (panjang * tinggi);
            TfLuas.setText(String.valueOf(luas));
            // KELILING
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            keliling = 4 * (panjang + lebar + tinggi);
            TfKeliling.setText(String.valueOf(keliling));
            // VOLUME
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            volume = panjang * lebar * tinggi;
            TfVolume.setText(String.valueOf(volume));
            
        }
        else if(CBLuas.isSelected() && CBKeliling.isSelected()){
            // LUAS
            panjang = Double.parseDouble(this.TfPanjang.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            luas = 2 * (panjang * lebar) + (lebar * tinggi) + (panjang * tinggi);
            TfLuas.setText(String.valueOf(luas));
            // KELILING
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            keliling = 4 * (panjang + lebar + tinggi);
            TfKeliling.setText(String.valueOf(keliling));
        }
        else if(CBKeliling.isSelected() && CBVolume.isSelected()) {
            // KELILING
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            keliling = 4 * (panjang + lebar + tinggi);
            TfKeliling.setText(String.valueOf(keliling));
            // VOLUME
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            volume = panjang * lebar * tinggi;
            TfVolume.setText(String.valueOf(volume));
        }
        else if (CBLuas.isSelected() && CBVolume.isSelected()){
            // LUAS
            panjang = Double.parseDouble(this.TfPanjang.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            luas = 2 *(panjang * lebar) + (lebar * tinggi) + (panjang * tinggi);
            TfLuas.setText(String.valueOf(luas));
            // VOLUME
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            volume = panjang * lebar * tinggi;
            TfVolume.setText(String.valueOf(volume));
        }
        else if (CBLuas.isSelected()) {
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            luas = 2 *(panjang * lebar) + (lebar * tinggi) + (panjang * tinggi);
            TfLuas.setText(String.valueOf(luas));
        }
        else if(CBKeliling.isSelected()) {
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            keliling = 4 * (panjang + lebar + tinggi);
            TfKeliling.setText(String.valueOf(keliling));
        }
        else if(CBVolume.isSelected()) {
            panjang = Double.parseDouble(this.TfPanjang.getText());
            lebar = Double.parseDouble(this.TfLebar.getText());
            tinggi = Double.parseDouble(this.TfTinggi.getText());
            volume = panjang * lebar * tinggi;
            TfVolume.setText(String.valueOf(volume));
        }
        else if (rumus.equals("")) {
            JOptionPane.showMessageDialog(null, 
                              "Tidak Boleh Kosong", 
                              "Alert", 
                              JOptionPane.WARNING_MESSAGE);
        }
        else {
            rumus = rumus.substring(0, rumus.length()-2) + ".";
            TfLuas.setText(String.valueOf(luas));
        }
        
        
    
    }//GEN-LAST:event_TfHitungActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        TfPanjang.setText("");
        TfLebar.setText("");
        TfTinggi.setText("");
        TfLuas.setText("");
        TfKeliling.setText("");
        TfVolume.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        Menu_Pilihan a = new Menu_Pilihan();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void TfPanjangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfPanjangKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
            evt.consume();
        }
    }//GEN-LAST:event_TfPanjangKeyTyped

    private void TfLebarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfLebarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
            evt.consume();
        }
    }//GEN-LAST:event_TfLebarKeyTyped

    private void TfTinggiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfTinggiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
            evt.consume();
        }
    }//GEN-LAST:event_TfTinggiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Balok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBKeliling;
    private javax.swing.JCheckBox CBLuas;
    private javax.swing.JCheckBox CBVolume;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton TfHitung;
    private javax.swing.JTextField TfKeliling;
    private javax.swing.JTextField TfLebar;
    private javax.swing.JTextField TfLuas;
    private javax.swing.JTextField TfPanjang;
    private javax.swing.JTextField TfTinggi;
    private javax.swing.JTextField TfVolume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
